### ISSUE TITLE
./insert-missing.php 'Timeout exceeded.' from BaseX

### ISSUE THREAD

**Issue by kumy** [GeoKretyMap/Api#17]
# php5 ./insert-missing.php 
# Backup databases

== Database connect
=== Insert into 'geokrety'
=== Insert into 'geokrety-details'
PHP Fatal error:  Uncaught exception 'Exception' with message 'Timeout exceeded.' in /home/kumy/GIT/Api/php/lib/BaseXClient.php:185
Stack trace:
#0 /home/kumy/GIT/Api/php/lib/BaseXClient.php(144): Query->exec('?', '1')
#1 /home/kumy/GIT/Api/php/insert-missing.php(44): Query->execute()
#2 {main}

  thrown in /home/kumy/GIT/Api/php/lib/BaseXClient.php on line 185

**Comment by kumy** [comment]
http://docs.basex.org/wiki/Options#TIMEOUT

The read part in the query should be the problem...

**Comment by kumy** [comment]
Script must be directly run in baseX console as admin, so it doesn't timeout
